version: "3"
services:
  mongodb:
    restart: unless-stopped
    container_name: indonesia-nl-mongo
    image: mongo
    ports:
      - "27017:27017"
    expose:
      - '27017'
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
  mongo-express:
    restart: unless-stopped
    depends_on:
      - mongodb
    container_name: indonesia-nl-mongo-express
    image: mongo-express
    ports:
      - "8080:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - redis-data:/data/
volumes:
  mongo-data:
    driver: local